name: CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node: [16, 17, 18]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node | ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          # ${{ matrix.node }}
          node-version: 18
          cache: 'npm'
      - run: npm install
      - run: npm run test

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses:  aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: arn:aws:iam::897729119853:role/ecr_role
          aws-region: us-east-2

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      # - name: Login into container docker registry
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     tags: vitorshermon/rocketseat-ci-api:${{ steps.generate_tag.outputs.sha }}, vitorshermon/rocketseat-ci-api:latest

      - name: Build docker image
        id: build-docker-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          TAG: ${{ steps.generate_tag.outputs.sha }}
        run: | 
          docker build -t $REGISTRY/shermon-ci-api:$TAG .
          docker push $REGISTRY/shermon-ci-api:$TAG
          docker tag $REGISTRY/shermon-ci-api:$TAG $REGISTRY/shermon-ci-api:latest
          docker push $REGISTRY/shermon-ci-api:latest
          IMAGE=$(echo $REGISTRY/shermon-ci-api:$TAG)
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
      
      - name: Deploy to App Runner
        id: deploy-app-runner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: shermon-api
          image: ${{ steps.build-docker-image.outputs.image }}
          access-role-arn: arn:aws:iam::897729119853:role/app-runner-role
          region: us-east-2
          cpu: 1
          memory: 2
          port: 3000
          wait-for-service-stability-seconds: 180

      - name: App runner check
        run: echo "App runner running... ${{ steps.deploy-app-runner.outputs.service-url }}"

      # - name: Push Image
      #   run: docker push vitorshermon/rocketseat-ci-api:${{ steps.generate_tag.outputs.sha }}
